# Embedded file name: lib.coginvasion.distributed.CogInvasionDoGlobals
DO_ID_COGINVASION = 1000
DO_ID_CLIENT_SERVICES_MANAGER = 1001
DO_ID_LAUNCHER_LOGIN_MANAGER = 1002
DO_ID_DISTRICT_NAME_MANAGER = 1003
DO_ID_FRIENDS_MANAGER = 1004